### ISSUE TITLE
Getting Error: Instruments crashed on startup at Instruments.onInstrumentsExit - when trying to open appium inspector

### ISSUE THREAD

**Issue by priyanka-agarwal** [saucelabs/docs#101]
I am getting error when trying to open Appium Inspector :

Error: Instruments crashed on startup at Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:398:31)

I am using Xcode 5 and appium - 1.0 and MAC OS X 10.9.

Please help .

**Comment by colinsauce** [comment]
hello @priyanka-agarwal,

Could you let us know which page of the docs brought you to this error? I'd like to reproduce it and improve our documentation so yourself and others will have an easier time with our Documentation.

**Comment by priyanka-agarwal** [comment]
Hi ,

I am getting this error once I have launched the appium server and then I am trying to open the Appium Inspector . When I am clicking on the "i" icon on the Appium UI to launch the Inspector the Simulator is launched , however when it is trying to load the .apk it is unable to do so . It is throwing the error :

info: Error: Instruments crashed on startup
    at Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:398:31)
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:328:12)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
info: Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}

Also can you can tell me which is the docs file you are referring here .

I am trying to do it on : Simulator ,
Xcode 5.0
Appium 1.0

**Comment by colinsauce** [comment]
hello @priyanka-agarwal I'm sorry about the troubles. This question sounds like a problem with Appium and not the Sauce Labs Documentation themselves. It would be best guided to the Appium discussion group found here: https://discuss.appium.io/
