### ISSUE TITLE
Issue with Appium Tutorial

### ISSUE THREAD

**Issue by gustavoriveray** [saucelabs/docs#102]
Curl command 

curl -L https://raw.github.com/saucelabs/appium-tutorial/master/bin/install_tutorial_android_ruby.sh | bash -s

suggested to run to install a .rb file installs a .rb file without any code. It just says "Not found"

**Comment by jlipps** [comment]
a workaround is to change the link to https://raw.githubusercontent.com/saucelabs/appium-tutorial/master/bin/install_tutorial_android_ruby.sh

**Comment by gustavoriveray** [comment]
same thing, in fact the first one, redirectsto the workaround suggested

**Comment by jlipps** [comment]
what system are you on?

**Comment by gustavoriveray** [comment]
Mac OSX 10.10

**Comment by jlipps** [comment]
Does the output of

> curl -L https://raw.githubusercontent.com/saucelabs/appium-tutorial/master/bin/install_tutorial_android_ruby.sh

Look like a ruby file?

**Comment by gustavoriveray** [comment]
no, it looks like bash script

  #!/usr/bin/env bash

  # remote invocation:
  # curl -L https://raw.github.com/saucelabs/appium-tutorial/master/bin/install_tutorial_android_ruby.sh | bash


  # don't install all the documentation at the moment
  GEM_INSTALL_OPTS="--no-ri --no-rdoc"
  TEST_FILE_URL=https://raw.github.com/appium/appium/master/sample-code/examples/ruby/android_on_sauce.rb


  if ! which ruby > /dev/null; then
    echo "No Ruby installation found"
    exit
  fi

  # sudo gem install rspec selenium-webdriver net-http-persistent rest_client

  if ! gem list rspec | grep '^rspec (' > /dev/null; then
    echo "* Installing RSpec gem"
    gem install $GEM_INSTALL_OPTS rspec
  fi

**Comment by jlipps** [comment]
OK, please try again--I've updated the incorrect URL in this script

**Comment by gustavoriveray** [comment]
Im still getting the file AndroidSauce.rb file with the content
    Not Found

**Comment by jlipps** [comment]
Aha. It's because the Appium sample-code repo had moved. Please try once more.

**Comment by gustavoriveray** [comment]
Solved (y). Thanks
