### ISSUE TITLE
Issue with Node.js Tutorial

### ISSUE THREAD

**Issue by biggerveggies** [saucelabs/docs#110]
Unsure what has happened (as I am a novice), but this tutorial no longer works for either OS X Yosemite or CentOS 7.  If you try and grunt the default task, you will get a message that 'Task "test:sauce:chrome" is not found.  I have a feeling that one of the packages/frameworks has changed which is causing issues. 

These were the steps I followed:

Install: 
• Clean CentOS 7 DVD ISO
• Software update run
• su root and installed node.js (curl -sL https://rpm.nodesource.com/setup | bash -) and (yum install -y nodejs)
• installed git (sudo yum install git) 
• exited root and installed modules (npm install -g mocha grunt grunt-init grunt-cli)
• made tutorial directory and (git clone https://github.com/saucelabs/grunt-init-sauce.git ~/.grunt-init/sauce)
• npm install
• grunt

Output: Warning: Task "test:sauce:chrome" not found. Use --force to continue.

I've tried this on two OS X machines and the above on a CentOS VM.

**Comment by colinsauce** [comment]
Hey @biggerveggies thanks for writing in and providing the awesome steps!

I have tried the tutorial myself and noticed it doesn't work for me either. I have created an internal ticket to help resolve this issue.

Sorry for the troubles,
Colin

**Comment by grommett** [comment]
Hey @biggerveggies see issue #107. I had the same issue as you mentioned and changing loadash version in ```package.json``` to ```"lodash": "~2.4.1"``` as @pfeilbr recommended fixed the issue for me.

**Comment by Jonahss** [comment]
fixed in saucelabs/grunt-init-sauce#5
