### ISSUE TITLE
Issue with Sauce Connect

### ISSUE THREAD

**Issue by seancunningham** [saucelabs/docs#134]
Hi there,
We are having an issue with our mocha tests starting while using Safari 8 as a platform with the karma-sauce-launcher plugin. We have tried all other combinations of Windows 8.1/8/7 and Mac OSx 10.10/10.9 with Chrome 43/42/41, Firefox  36/35/34, and Safari 7 - which do not seem to have this issue. Locally, we have also tested Safari 8 with success - so we are sure that it is not an issue with the actual browser. I have read through posts on stack-exchange which recommend increasing the browser timeout limit, as well as disconnection limits, but these fixes do not seem to work for this specific browser. 
Any advice would be very appreciated,
Thanks.

**Comment by colinsauce** [comment]
hello @seancunningham this looks like a support request. Could you please write into us here; https://support.saucelabs.com/home.

This space is meant for errors with docs.saucelabs.com.

Thanks for your understanding,
Colin
