### ISSUE TITLE
Bamboo Integration Guide Issue

### ISSUE THREAD

**Issue by angelsmercy** [saucelabs/docs#136]
Within the [Bamboo Integration Guide](https://docs.saucelabs.com/ci-integrations/bamboo/)

at the following point:
```
Click the Command link.
Enter Run Tests in the Task Description field.
Click on the Add Executable link.

Enter --with-nosexunit simple_test.py in the Argument field.
```

You fail to mention _which_ executable command this applies to.  It could use an accompanying screen shot to show which Executable the above arguments apply to.

**Comment by DylanLacey** [comment]
Good point.  I *think* this should be `nosetests`.

**Comment by rossrowe** [comment]
Thanks for raising this, I've just submitted a pull request which adds the missing step regarding the nosetests executable
