### ISSUE TITLE
Issue with Sauce Connect: 

### ISSUE THREAD

**Issue by ananthoju** [saucelabs/docs#145]
I am seeing following error when I try to run my test case on Sauce Labs on Windows 7 platform.
I didn't see the unspecified Device error before, tried to put Desired-capabilities for device with many names for windows but couldn't succeeded. 

Message
SetUp : OpenQA.Selenium.WebDriverException : Unexpected error. Unsupported OS/browser/version/device combo: OS: 'Windows 2003', Browser: 'googlechrome', Version: '42.', Device: 'unspecified', Screen Resolution: '1680x1050'
Stack Trace
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

Thanks,
Jaydev

**Comment by colinsauce** [comment]
hello @ananthoju,

This looks like a support issue and not an issue with the docs themselves.

Could you please reach out to us here https://support.saucelabs.com/home ?

Colin

**Comment by ananthoju** [comment]
Thanks for the update, Colin.
Besides, its a simple fix, SauceLabs doesnt have support for chrome version 42 and its shows weird error as above when it cant support a version of browser.

**Comment by colinsauce** [comment]
Hey @ananthoju we are working on Chrome 42 as we speak :). Glad to hear 41 is working fine.
