### ISSUE TITLE
Issue with Selenium Builder

### ISSUE THREAD

**Issue by michaelckelly** [saucelabs/docs#147]
http://sebuilder.github.io/se-builder/ & https://github.com/SeleniumBuilder/se-builder are bad links - they both 404.

The correct links are http://seleniumbuilder.github.io/se-builder/ and https://github.com/SeleniumBuilder/se-builder.

These links are found on https://docs.saucelabs.com/reference/selenium-builder/.

**Comment by DylanLacey** [comment]
I've made those changes, they'll go out in the next deploy ^_^ FYI we :heart_eyes_cat: pull requests for our docs;  It can often be easier to send those then describe changes, and you're welcome to do so.

Thanks again!
