### ISSUE TITLE
Browser status for build is broken

### ISSUE THREAD

**Issue by monolithed** [saucelabs/docs#149]
![1430348064842](https://cloud.githubusercontent.com/assets/803674/7403183/e61606f6-eedb-11e4-8bed-ef816597a34d.png)

![1430348469261](https://cloud.githubusercontent.com/assets/803674/7403283/cf986ff8-eedc-11e4-9bd2-52f0e321ea61.png)
![1430348419852](https://cloud.githubusercontent.com/assets/803674/7403284/cfb034c6-eedc-11e4-8fee-c9c4a9550c2f.png)

I can't see my [status page](https://saucelabs.com/u/monolithed).

**Comment by colinsauce** [comment]
Hello @monolithed,
I see you opened support ticket https://saucelabs.zendesk.com/agent/tickets/20547. Can we work to resolve this there?
Colin

**Comment by monolithed** [comment]
@colinsauce, sure.
