### ISSUE TITLE
tutorial Travis CI

### ISSUE THREAD

**Issue by xgbuils** [saucelabs/docs#159]
I'm reading tutorial of [Travis CI in Sauce Labs](https://docs.saucelabs.com/ci-integrations/travis-ci/) and there is a broken link:
> If you want to learn more about secure environment variables, check out the [Travis CI documentation](http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables).

`#Secure-environment-variables` is not a section of http://docs.travis-ci.com/user/build-configuration/

Regards!

**Comment by colinsauce** [comment]
hey @xgbuils thanks for reporting this!

I've got a PR in the works; https://github.com/saucelabs/docs/pull/161

Will that help you out?
Colin

**Comment by xgbuils** [comment]
Thank you @colinsauce!
