### ISSUE TITLE
Explain how status image keep track of branches

### ISSUE THREAD

**Issue by bitinn** [saucelabs/docs#166]
One thing I failed to find in the doc is how browser matrix badge would be updated when there are PR from other developers. Given sauce labs doesn't have a concept of git branch, does all PR's test reflect in our browser matrix badge?

eg. If I have Travis CI integrated with Sauce Labs and it runs on every PR we receive, can broken PR break our all-green browser matrix? If so, how do we avoid it so that it only show test result from master, which should always be green?

PS: we use [zuul](https://github.com/defunctzombie/zuul) but I am not sure whether to raise this issue to zuul or travis or your guys, but since the badge is from you guys, I decide to ask here first.

- my project https://github.com/bitinn/vdom-parser
- sauce labs doc https://docs.saucelabs.com/reference/status-images/#adding-the-browser-matrix-widget

**Comment by DylanLacey** [comment]
G'day!

Unfortunately, at the moment there's no way to get build specific browser matrixes;  The matrix will reflect whatever the latest 'build' showed.

I've put a suggestion into our Feature Request portal: https://saucelabs.ideas.aha.io/ideas/SLIDEA-I-44.  This portal is managed directly by our product managers, and users can vote features up and express their feedback.  I've used your GitHub email address as the email of the feature, so you will get updates.

Sorry we can't help directly yet;  Hopefully we'll be able to offer something more suitable soon.
