### ISSUE TITLE
Issue with Jenkins Integration

### ISSUE THREAD

**Issue by upgundecha** [saucelabs/docs#168]
Hi,

I want to setup a multi-configuration project for Appium tests with Sauce Labs Jenkins Plug-In.

Where do we get complete reference of environment variable for Appium? I don't see or relate following variables in this document.

- appiumVersion
- deviceName
- deviceOrientation
- platformVersion
- platformName
- browserName
- name

It would be great to add Appium specific environment variable as well to this document.

Thanks,
Unmesh

**Comment by colinsauce** [comment]
Please make an issue request with the plugin itself.
The github repo for it is here; https://github.com/jenkinsci/sauce-ondemand-plugin
The place to make an issue would be here; https://issues.jenkins-ci.org/browse/JENKINS/component/15751/?selectedTab=com.atlassian.jira.jira-projects-plugin:component-summary-panel

**Comment by albedithdiaz** [comment]
I agree with @colinsauce 

Information about how the plugin works should be provided by the plugin itself, thus submitting an issue requesting this documentation from the plugin developers would be a great start and in the long run will also help a lot of people.

Currently Sauce Labs doesn't have a Jenkins + Appium tutorial that could help as a guidance. The best help we currently have for this case is an iOS and Android test code, which has detail comments related to using Appium, Jenkins and the Sauce Labs Jenkins Plugin.

Find it here in my Github repository: https://github.com/albedithdiaz/JenkinsTests/blob/master/iOS_SaucePlugin.py
https://github.com/albedithdiaz/JenkinsTests/blob/master/Android_SaucePlugin.py

I have noticed that everything becomes easier after you figure out how to properly set the correct desired capabilities using the Environment Variables from the Sauce Labs Jenkins Plugin. Overall the desired capabilities should match the desired capabilities provided by the Platform Configurator: https://docs.saucelabs.com/reference/platforms-configurator/#/

**Comment by upgundecha** [comment]
Thanks @colinsauce @albedithdiaz I'll raise this with plug-in. 
I was looking for issue tracker at plug-in repo in GitHub, but didn't realise this tracked on Jenkins site.

It's worth to have a table explaining this mapping in docs.
