### ISSUE TITLE
Issue with controlling execution on newly opened browser in cloud !

### ISSUE THREAD

**Issue by nk0017860** [saucelabs/docs#180]
Hi,

I am executing my selenium scripts on Sauce cloud. There are couple of steps where new browser opens up and we have to swtich control to newly opened browser, perform certain actions and close it and move back to original browser.
To achieve this, I am using "driver.switchTo().window(winList[1])" created using "driver.getWindowHandles();".
This code works fine when I am executing locally. However, when I execute it cloud, the driver.getWindowHandles(); returns nothing and control does not switch to new browser window and my test script fails.
Can you tell me how do I handle this thing in cloud?

Awaiting your quick response

Nachiket K

**Comment by colinsauce** [comment]
hey @nk0017860 this does not seem to be a specific problem with the docs pages, but more a problem with selenium implementation. 

Could you please reach out to support?
https://support.saucelabs.com/
