### ISSUE TITLE
Add all the properties available in the example? [js-tests]

### ISSUE THREAD

**Issue by Mouvedia** [saucelabs/docs#188]
I am talking about the single request example here: https://docs.saucelabs.com/reference/rest-api/#start-js-unit-tests

**Comment by saucyallison** [comment]
You can add extra desired capabilities to the `--data` parameter - here is how you would add the build version to the example:

```
curl https://saucelabs.com/rest/v1/awilbur/js-tests \
-X POST \
-u username:access-key \
-H 'Content-Type: application/json' \
--data '{
    "platforms": [["Windows 7", "firefox", "27"],
                 ["Linux", "googlechrome", ""]],
    "url": "https://saucelabs.com/test_helpers/front_tests/index.html",
    "build": "mybuild111",
    "framework": "jasmine"}'
```

Additional options for desired capabilities can be found on the [Test Configuration page](https://docs.saucelabs.com/reference/test-configuration). Hope this helps!
