### ISSUE TITLE
Issue with Ruby Tutorial

### ISSUE THREAD

**Issue by smparekh** [saucelabs/docs#213]
SauceWhisk::Jobs.change_status job_id, !example.exception.nil?

Should this be:

    SauceWhisk::Jobs.change_status job_id, example.exception.nil?

Since if exception == nil we want the job status to be true?

**Comment by DylanLacey** [comment]
Yup, you're totally right; Thanks!  Binary is hard :P

**Comment by DrPhilG** [comment]
Hi Shaishav, I asked the developer who wrote the tutorial to check, and he updated the tutorial. Thanks for bringing this to our attention!

Phil 

Phil Gochenour, PhD
Senior Technical Writer 
philg@saucelabs.com <mailto:philg@saucelabs.com>
Sauce Labs <http://saucelabs.com/> | Sauce blog <http://sauceio.com/>
